### ISSUE TITLE
Added support for get skin by name

### ISSUE THREAD

**Issue by LemonPAKA** [syorito-hatsuki/bluemap-custom-skin-server#3]
I change "customSkinserverurl" from"http://localhost/" to "https://auth.mc-user.com:233/f34896540b0211ed9cdc00163e095b49/sessionserver/session/minecraft/profile/"

player data should be https://auth.mc-user.com:233/f34896540b0211ed9cdc00163e095b49/sessionserver/session/minecraft/profile/db34ec2d6d0c3e42923e99fa9dad3cf5
(I checked the json it return is the same format as Mojang one)
I decoded that base64 value it also is same format as mojang one...
![QQ截图20220814211243](https://user-images.githubusercontent.com/17202894/184539347-52e7fef4-d6bb-4e19-98ea-a24df0f5ff6c.png)
![QQ截图20220814211144](https://user-images.githubusercontent.com/17202894/184539336-fcdfd68e-2774-444c-85eb-6d2994135557.png)
![QQ截图20220814211022](https://user-images.githubusercontent.com/17202894/184539340-37636cf0-2982-4d68-b402-f1b5199809a8.png)
![QQ截图20220814211134](https://user-images.githubusercontent.com/17202894/184539343-ab3db320-141b-47dc-b8cb-b377c0b87a27.png)
![QQ截图20220814211106](https://user-images.githubusercontent.com/17202894/184539344-a38e4938-ce04-4414-a956-8c3c0fc4be17.png)

**Comment by syorito-hatsuki** [comment]
As URL output need to be path to image. I just writing own universal PHP script layer. That why mod is still alpha

**Comment by syorito-hatsuki** [comment]
Also I think in future add stock support of most popular Skin Servers for Minecraft

**Comment by LemonPAKA** [comment]
> As URL output need to be path to image. I just writing own universal PHP script layer. That why mod is still alpha

some skin "stealer" web use Player Nickname to output skin png file... maybe add name support will be a fast way for now

**Comment by syorito-hatsuki** [comment]
> > As URL output need to be path to image. I just writing own universal PHP script layer. That why mod is still alpha
> 
> some skin "stealer" web use Player Nickname to output skin png file... maybe add name support will be a fast way for now

I wanted to add it. But Blue (BlueMap author) writes multiplatform code. So changing only one Implementation is hard. I have tried already but currently, it is not possible. I add in the next update `auth.mc-user.com` server and some other support without URL. Because all servers have different outputs it is hard to do universal.

**Comment by LemonPAKA** [comment]
> > > As URL output need to be path to image. I just writing own universal PHP script layer. That why mod is still alpha
> > 
> > 
> > some skin "stealer" web use Player Nickname to output skin png file... maybe add name support will be a fast way for now
> 
> I wanted to add it. But Blue (BlueMap author) writes multiplatform code. So changing only one Implementation is hard. I have tried already but currently, it is not possible. I add in the next update `auth.mc-user.com` server and some other support without URL. Because all servers have different outputs it is hard to do universal.

auth.mc-user.com is a third-party login system...they use server tags to distinguish different servers...for allowing player use different nickname and skin in different server...that is a weird system...for example my server tag is "f34896540b0211ed9cdc00163e095b49", others have different one...So I think you have no need to support it at this time...

**Comment by syorito-hatsuki** [comment]
Okei I renamed Issue

**Comment by syorito-hatsuki** [comment]
https://littleskin.cn
https://skin.prinzeugen.net
https://ely.by
http://www.skinme.cc
https://games.glitchless.ru

3rd server for coming update

**Comment by syorito-hatsuki** [comment]
Added in update 2022.8.1
