### ISSUE TITLE
Can not work correctly in 1.20.4 Fabric 0.15.6

### ISSUE THREAD

**Issue by HIM049** [syorito-hatsuki/bluemap-custom-skin-server#7]
> Minecraft: 1.20.4
> Fabric: 0.15.6
> FabricAPI: 0.95.0
> Fabric-language-kotlin-1.10.17+kotlin.1.9.22.jar
> Bluemap: 3.20
> BCSS: 3032.11.1

Here is my config file:
![config](https://github.com/syorito-hatsuki/bluemap-custom-skin-server/assets/67405384/bf2c86d3-e9fe-4ab3-9fc4-4a8435a30a84)

Here is my server log:
![log](https://github.com/syorito-hatsuki/bluemap-custom-skin-server/assets/67405384/788b2e13-ae21-44cc-9e90-5f6f49ff5218)

When player join the server, the following error message appears in the terminal，and the player's skin cannot be loaded correctly. I have tried to enable debug output, but there is no more helpful information.

**Comment by syorito-hatsuki** [comment]
The link that you provided in config returns "Page not found". You can always debug links in the browser.

That service requires a URL in the format https://skin.usla.cn/avatar/%username%
But it will still not work because BlueMap requires a skin file 64x64 image of the skin, not head/avatar only. 

Not all services have that kind of link. The best practice is asking about that service support

**Comment by HIM049** [comment]
Okay. Thanks a lot

**Comment by HIM049** [comment]
I fixed my skin service. Now you can get player's skin correctly when you requires URL like `https://skin.usla.cn/skin/Misakra`.
But when I test this URL in my Minecraft server, there are some error message same as before.
I'm sure I changed config file and reboot the Minecraft server.

**Comment by syorito-hatsuki** [comment]
> I fixed my skin service. Now you can get player's skin correctly when you requires URL like `https://skin.usla.cn/skin/Misakra`. But when I test this URL in my Minecraft server, there are some error message same as before. I'm sure I changed config file and reboot the Minecraft server.

![image](https://github.com/syorito-hatsuki/bluemap-custom-skin-server/assets/33298273/79a07bab-0eaa-4c75-8b66-ce08e6c68fc1)

**Comment by HIM049** [comment]
emm, change another name is ok.
![{7F18BC10-D8C7-4ad4-BC9C-EAA73F171366}](https://github.com/syorito-hatsuki/bluemap-custom-skin-server/assets/67405384/5e49dba9-be44-4f7d-a0fc-95afac8116b3)

**Comment by syorito-hatsuki** [comment]
> https://skin.usla.cn/skin/Misakra

Ye. If you login to server with name HIM049 it gonna work, but not with Misakra because skin with that name not available.

**Comment by HIM049** [comment]
The player named Misakra changed name after I write response. HIM049 is my account, and I have been use this account for testing.
